version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "vcpkg"
    directories:
      - "/native_lib"
      - "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directories:
      - "/frontend"
      - "/circuit_solver_proto"
      - "/ffi_bridge"
    schedule:
      interval: "weekly"
