// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Solves a circuit supplied as a binary protobuf buffer.
///
/// On success returns 0, writes the solved binary protobuf to *outputBuffer
/// and its length to *outputLength. The caller must free the output buffer
/// with destroyGraphBuffer().
///
/// On failure returns a non-zero error code. Call getErrorMessage() for a
/// human-readable description.
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external int solveGraphFromBuffer(
  ffi.Pointer<ffi.Void> inputBuffer,
  int inputLength,
  ffi.Pointer<ffi.Pointer<ffi.Void>> outputBuffer,
  ffi.Pointer<ffi.Size> outputLength,
);

/// Frees a buffer previously returned by solveGraphFromBuffer().
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void destroyGraphBuffer(ffi.Pointer<ffi.Void> graphBuffer);

/// Frees a JSON string previously returned by the C solveGraphFromJson().
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void destroyGraphJson(ffi.Pointer<ffi.Char> graphJson);

/// Solves a circuit supplied as a JSON string.
///
/// On success returns 0 and writes the solved JSON to *outputJson. The caller
/// must free the string with destroyGraphJson().
///
/// On failure returns a non-zero error code.
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
>()
external int solveGraphFromJson(
  ffi.Pointer<ffi.Char> inputJson,
  ffi.Pointer<ffi.Pointer<ffi.Char>> outputJson,
);

/// Returns a human-readable description for the given error code.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> getErrorMessage(int errorNumber);

const int CIRCUITSOLVER_ERROR_INVALID_INPUT = 1;

const int CIRCUITSOLVER_ERROR_NO_SOLUTION = 2;

const int CIRCUITSOLVER_ERROR_FAILED_SERIALIZATION = 3;
