# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml for multi-platform support
name: Build with CMake
on:
  push:
    branches: ["flutter-app"]
  pull_request:
    branches: ["main"]
    paths:
      - native_lib
env:
  # CMake build type
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: lukka/get-cmake@latest
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgConfigurationJsonGlob: "**/native_lib/vcpkg-configuration.json"
          doNotCache: false

      - name: Restore Vcpkg Cache
        id: restore-build-cache
        uses: actions/cache/restore@v6
        with:
          path: native_lib/build/vcpkg_installed
          key: ${{ runner.os }}-${{ hashFiles('**/vcpkg.json', '**/vcpkg-configuration.json')}}

      - name: Configure CMake
        run: cmake native_lib --preset vcpkg -DCIRCUITSOLVER_BUILD_TESTS=ON -DCIRCUITSOLVER_TEST_COVERAGE=ON

      - name: Save Vcpkg Cache
        uses: actions/cache/save@v6
        with:
          path: native_lib/build/vcpkg_installed
          key: ${{ steps.restore-build-cache.outputs.cache-primary-key }}

      - uses: actions/upload-artifact@v4
        name: Upload compile_commands.json
        with:
          name: native-lib-compile-commands
          path: native_lib/build/compile_commands.json

      - name: Build with CMake
        run: cmake --build native_lib/build

      - name: Test
        run: ctest native_lib

      - name: Generate Cobertura Report
        uses: threeal/gcovr-action@v1.2.0
        with:
          root: native_lib
          xml-out: cobertura.xml

      - uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        with:
          name: cobertura-report
          path: cobertura.xml

  upload-coverage:
    needs: build
    if: ${{ !cancelled() && needs.build.result == 'success' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      code-quality: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cobertura-report

      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cobertura.xml
  review:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: native-lib-compile-commands
      # This needs compile_commands.json to already be generated
      - uses: ZedThree/clang-tidy-review@v0.23.1
        if: github.event_name == 'pull_request'
        id: review
        with:
          build_dir: ./build
          base_dir: ${{ github.workspace }}/native_lib

      # Uploads an artefact containing clang_fixes.json
      - uses: ZedThree/clang-tidy-review/upload@v0.23.1
        if: github.event_name == 'pull_request'
        id: upload-review

      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1
