name: native_lib Tests
on:
  push:
    branches: ["main"]
    paths:
      - native_lib/**/*.cpp
      - native_lib/**/*.h
      - native_lib/vcpkg.json
  pull_request:
    branches: ["main"]
    paths:
      - native_lib/**/*.cpp
      - native_lib/**/*.h
      - native_lib/vcpkg.json
env:
  # CMake build type
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: "native_lib/vcpkg.json"
          doNotCache: false
      - uses: aminya/setup-cpp@v1
        with:
          compiler: llvm-22
          cmake: 4.4.0
          ninja: true
      - name: Restore Vcpkg Cache
        id: restore-build-cache
        uses: actions/cache/restore@v6
        with:
          path: native_lib/build/vcpkg_installed
          key: ${{ runner.os }}-${{ hashFiles('native_lib/vcpkg.json') }}

      - name: Configure CMake
        run: cmake native_lib --preset tests

      - name: Save Vcpkg Cache
        uses: actions/cache/save@v6
        with:
          path: native_lib/build/vcpkg_installed
          key: ${{ steps.restore-build-cache.outputs.cache-primary-key }}

      - uses: actions/upload-artifact@v4
        name: Upload compile_commands.json
        with:
          name: native-lib-compile-commands
          path: native_lib/build/compile_commands.json

      - name: Build with CMake
        run: cmake --build native_lib/build

      - name: Test
        run: ctest --test-dir native_lib/build

      - name: Generate Coverage Report
        run: |
          "llvm-profdata" merge -sparse native_lib/build/*.profraw -o coverage.profdata
          "llvm-cov" export -format=lcov -instr-profile=coverage.profdata ./native_lib/build/circuitsolverTests > coverage.info

      - uses: codecov/codecov-action@v7
        with:
          gcov_executable: ${{ env.GCOV }}
          gcov_include: native_lib/src,native_lib/include
          token: ${{ secrets.CODECOV_TOKEN }}

  review:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: native-lib-compile-commands
      # This needs compile_commands.json to already be generated
      - uses: ZedThree/clang-tidy-review@v0.23.1
        if: github.event_name == 'pull_request'
        id: review
        with:
          build_dir: ./build
          base_dir: ${{ github.workspace }}/native_lib

      # Uploads an artefact containing clang_fixes.json
      - uses: ZedThree/clang-tidy-review/upload@v0.23.1
        if: github.event_name == 'pull_request'
        id: upload-review

      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1
